FROM node:24-alpine AS base

RUN npm install -g bun


WORKDIR /usr/src/app

COPY ./package.json ./package.json
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json
COPY ./turbo.json ./turbo.json
COPY ./packages ./packages
COPY ./apps/frontend ./apps/frontend

RUN bun install

RUN bun run db:generate

WORKDIR /usr/src/app

RUN bun run build

EXPOSE 3000

CMD ["pnpm", "run", "start:drawnew"]